apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-scope
  labels:
    app: kube-scope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-scope
  template:
    metadata:
      labels:
        app: kube-scope
    spec:
      containers:
      - name: kube-scope
        image: hharnisc/kube-scope:b8d16fab8c41ecd69895b6ab0336e1e2670d2b0b
        ports:
        - containerPort: 3000
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
