apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-scope
  labels:
    app: kube-scope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-scope
  template:
    metadata:
      labels:
        app: kube-scope
    spec:
      containers:
      - name: kube-scope
        image: hharnisc/kube-scope:fbe16b09ff11432b963f88d6409fce5dee6c689b
        ports:
        - containerPort: 3000
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_CADVISOR_PORT
          value: "4194"
